// Auto-generated by: npx supabase gen types typescript --project-id getwbaktcbwntsbgyeso
// Run this command after every schema migration to keep types in sync.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      pharmacies: {
        Row: {
          id: string
          name: string
          logo_url: string | null
          address: string | null
          gst_number: string | null
          phone: string | null
          currency: string
          timezone: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          logo_url?: string | null
          address?: string | null
          gst_number?: string | null
          phone?: string | null
          currency?: string
          timezone?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['pharmacies']['Insert']>
      }
      profiles: {
        Row: {
          id: string
          pharmacy_id: string | null
          full_name: string | null
          role: 'owner' | 'manager' | 'pharmacist' | 'cashier' | null
          created_at: string
        }
        Insert: {
          id: string
          pharmacy_id?: string | null
          full_name?: string | null
          role?: 'owner' | 'manager' | 'pharmacist' | 'cashier' | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      categories: {
        Row: {
          id: string
          pharmacy_id: string
          name: string
        }
        Insert: {
          id?: string
          pharmacy_id: string
          name: string
        }
        Update: Partial<Database['public']['Tables']['categories']['Insert']>
      }
      medicines: {
        Row: {
          id: string
          pharmacy_id: string
          name: string
          generic_name: string | null
          category_id: string | null
          manufacturer: string | null
          barcode: string | null
          batch_number: string | null
          expiry_date: string | null
          purchase_price: number | null
          sale_price: number
          stock_quantity: number
          reorder_level: number
          prescription_required: boolean
          unit: string
          deleted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          pharmacy_id: string
          name: string
          generic_name?: string | null
          category_id?: string | null
          manufacturer?: string | null
          barcode?: string | null
          batch_number?: string | null
          expiry_date?: string | null
          purchase_price?: number | null
          sale_price: number
          stock_quantity?: number
          reorder_level?: number
          prescription_required?: boolean
          unit?: string
          deleted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['medicines']['Insert']>
      }
      suppliers: {
        Row: {
          id: string
          pharmacy_id: string
          name: string
          contact_person: string | null
          phone: string | null
          email: string | null
          address: string | null
          gst_number: string | null
        }
        Insert: {
          id?: string
          pharmacy_id: string
          name: string
          contact_person?: string | null
          phone?: string | null
          email?: string | null
          address?: string | null
          gst_number?: string | null
        }
        Update: Partial<Database['public']['Tables']['suppliers']['Insert']>
      }
      customers: {
        Row: {
          id: string
          pharmacy_id: string
          name: string
          phone: string | null
          address: string | null
          created_at: string
        }
        Insert: {
          id?: string
          pharmacy_id: string
          name: string
          phone?: string | null
          address?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['customers']['Insert']>
      }
      purchases: {
        Row: {
          id: string
          pharmacy_id: string
          supplier_id: string | null
          invoice_number: string | null
          invoice_date: string
          total_amount: number | null
          paid_amount: number
          payment_status: string
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          pharmacy_id: string
          supplier_id?: string | null
          invoice_number?: string | null
          invoice_date: string
          total_amount?: number | null
          paid_amount?: number
          payment_status?: string
          created_by?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['purchases']['Insert']>
      }
      purchase_items: {
        Row: {
          id: string
          purchase_id: string
          medicine_id: string
          quantity: number
          unit_cost: number
          total_cost: number
        }
        Insert: {
          id?: string
          purchase_id: string
          medicine_id: string
          quantity: number
          unit_cost: number
          total_cost: number
        }
        Update: Partial<Database['public']['Tables']['purchase_items']['Insert']>
      }
      sales: {
        Row: {
          id: string
          pharmacy_id: string
          customer_id: string | null
          invoice_number: string | null
          sale_date: string
          subtotal: number | null
          discount: number
          tax: number
          total: number | null
          payment_method: string | null
          cashier_id: string | null
          prescription_id: string | null
        }
        Insert: {
          id?: string
          pharmacy_id: string
          customer_id?: string | null
          invoice_number?: string | null
          sale_date?: string
          subtotal?: number | null
          discount?: number
          tax?: number
          total?: number | null
          payment_method?: string | null
          cashier_id?: string | null
          prescription_id?: string | null
        }
        Update: Partial<Database['public']['Tables']['sales']['Insert']>
      }
      sale_items: {
        Row: {
          id: string
          sale_id: string
          medicine_id: string
          quantity: number
          unit_price: number
          discount: number
          total: number
        }
        Insert: {
          id?: string
          sale_id: string
          medicine_id: string
          quantity: number
          unit_price: number
          discount?: number
          total: number
        }
        Update: Partial<Database['public']['Tables']['sale_items']['Insert']>
      }
      prescriptions: {
        Row: {
          id: string
          pharmacy_id: string
          customer_id: string | null
          image_url: string | null
          doctor_name: string | null
          prescription_date: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          pharmacy_id: string
          customer_id?: string | null
          image_url?: string | null
          doctor_name?: string | null
          prescription_date?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['prescriptions']['Insert']>
      }
      audit_logs: {
        Row: {
          id: string
          pharmacy_id: string
          user_id: string | null
          action: string | null
          table_name: string | null
          record_id: string | null
          changes: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          pharmacy_id: string
          user_id?: string | null
          action?: string | null
          table_name?: string | null
          record_id?: string | null
          changes?: Json | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: {
      get_user_pharmacy_id: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Enums: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
